if (!process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY) {
  throw Error("NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY is missing!");
}

export const NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY =
  process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY;

if (!process.env.NEXT_PUBLIC_SUPABASE_URL) {
  throw Error("NEXT_PUBLIC_SUPABASE_URL is missing!");
}

export const NEXT_PUBLIC_SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;

if (!process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) {
  throw Error("NEXT_PUBLIC_SUPABASE_ANON_KEY is missing!");
}

export const NEXT_PUBLIC_SUPABASE_ANON_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
